services:
  
  walletbackend:
    build: .
    container_name: WalletBackend
    restart: always
    depends_on:
      - walletdb
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    ports:
      - "5000:5000"
      - "5001:5001"
     

  walletdb:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: WalletBackendDatabase
    restart: always
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
 
volumes:
  sql_data:
